### ISSUE TITLE
工具箱的祈愿统计有误

### ISSUE THREAD

**Issue by WillyerQ** [JamXi233/SRTools#1]
![image](https://github.com/JamXi233/SRTools/assets/126785476/2271816a-32c6-4272-bd4e-65ea91aaeb6e)
![image](https://github.com/JamXi233/SRTools/assets/126785476/903171ea-b194-44a6-a3a8-2cb3a81a0d6a)
如图，工具箱显示我才抽了20抽，但是实际上我已经抽了67抽了

**Comment by JamXi233** [comment]
请检查:
**是否在获取API数据时退出到应用其他界面
使用了不同的UID获取祈愿**

如果问题仍然存在，请发送以下内容到jamsg@qq.com，以便更快的定位问题所在
```
SRTools的备份文件[.SRToolsBackup]
导出的祈愿记录[Excel格式]
如果有能力的话，请再加上您对应UID的祈愿API地址
```
**感谢您的issue**

**Comment by JamXi233** [comment]
您似乎并没有给我发送邮件🤔
如果在1周后我仍未收到来自您的电子邮件，该issue将会被Close

**Comment by JamXi233** [comment]
由于您似乎并没有给我发送邮件，该issue将被关闭
