### ISSUE TITLE
打开后只显示这些

### ISSUE THREAD

**Issue by SynoGoop** [JamXi233/SRTools#11]
![image](https://github.com/JamXi233/SRTools/assets/7943704/81421343-ab35-4d8c-8b99-1013bc446212)
打开后只显示这些，在WindowsApp下打开的，直接在“开始”下显示
![image](https://github.com/JamXi233/SRTools/assets/7943704/936773dc-d430-41bb-b054-56affc3e9dc5)

**Comment by JamXi233** [comment]
系统的版本:Windows [XX] XXXXX.XXXX
用户类型:

**Comment by SynoGoop** [comment]
> 系统的版本:Windows [XX] XXXXX.XXXX 用户类型:

系统的版本:Windows 11 22631.2861
用户类型:管理员

**Comment by JamXi233** [comment]
是官方系统还是精简版的系统，用户是默认的Administrator吗

**Comment by SynoGoop** [comment]
> 是官方系统还是精简版的系统，用户是默认的Administrator吗

官方的，
![image](https://github.com/JamXi233/SRTools/assets/7943704/b506efa0-8eef-400c-9bbb-a0173aa3e187)

**Comment by JamXi233** [comment]
已经超过半年无人可复现该类问题，将关闭该issue。
