### ISSUE TITLE
【关于】starward

### ISSUE THREAD

**Issue by jinghuashang** [JamXi233/SRTools#13]
你这UI，不会是Starward 二改的吧

**Comment by JamXi233** [comment]
本项目与Starward无任何关系

**Comment by jinghuashang** [comment]
既然你说无任何关系，为何UI甚至布局都如此相似
![](https://imgbed.jinghuashang.cn/file/a4d7d5b9dd35738545d81.png)

**Comment by JamXi233** [comment]
但凡要是能看一看Commit、两个软件同对比同一时间段版本样式也不至于得出这种结论。

**Comment by jinghuashang** [comment]
都不用对比，Starward在你开库前就是这样的样式

**Comment by JamXi233** [comment]
那你可以去Starward那里开issue，说我二改。

**Comment by jinghuashang** [comment]
我想知道，你为什么做这种吃力不讨好的事，相比Starward的庞大开发团队，还为什么单开一个，

**Comment by NOWorEVER** [comment]
UI是UI。和软件内部代码有什么关系😓

**Comment by JamXi233** [comment]
> 我想知道，你为什么做这种吃力不讨好的事，相比Starward的庞大开发团队，还为什么单开一个，

没有为什么，仅因为去年那时还未出现可以解锁帧率，代理抽卡分析的工具而已。
