### ISSUE TITLE
严重错误

### ISSUE THREAD

**Issue by 2580m** [JamXi233/SRTools#14]
打开抽卡分析界面时大概率会出现此错误
![屏幕截图 2024-02-27 162314](https://github.com/JamXi233/SRTools/assets/109930302/f554499a-2f2d-476c-836c-efc193fec90b)
[SRTools_Panic_20240227_162030.zip](https://github.com/JamXi233/SRTools/files/14416522/SRTools_Panic_20240227_162030.zip)
错误日志以压缩为zip文件并上传。
系统版本：22631.3155
Microsoft账户
管理员账户

**Comment by JamXi233** [comment]
#10

**Comment by JamXi233** [comment]
已经解决 2896f9b79b1556b5a27b835e18b27c0e3833c169
