### ISSUE TITLE
安裝失敗

### ISSUE THREAD

**Issue by ghost** [JamXi233/SRTools#15]
![image](https://github.com/JamXi233/SRTools/assets/107019852/f268c1c2-9bf1-46de-9e9a-b8e95c57cf79)

您需要針對此應用程式套件所安裝的新憑證，或需要具有受信任憑證的新應用程式套件。您的系統管理員或應用程式開發人員可以協助您。已處理憑證鏈結，但憑證鏈結的處理卻因不受信任的根憑證而終止 (0x800B0109)

**Comment by JamXi233** [comment]
需要使用Powershell脚本进行安装[install.ps1]
