### ISSUE TITLE
首次运行无法更新数据

### ISSUE THREAD

**Issue by EvanBranty** [JamXi233/SRTools#17]
<img width="760" alt="屏幕截图 2024-03-12 215337" src="https://github.com/JamXi233/SRTools/assets/52557408/6fb44d37-3a46-49d4-9f72-a58842baae53">

**Comment by EvanBranty** [comment]
<img width="287" alt="屏幕截图 2024-03-12 221053" src="https://github.com/JamXi233/SRTools/assets/52557408/3e6817c0-e2e9-4139-b6fd-a777bfa7f4fd">
似乎只能选择一个更新渠道

**Comment by JamXi233** [comment]
我这里暂时并未成功复现该问题，也有可能是网络原因，可以再重试几次。

**Comment by EvanBranty** [comment]
欧克欧克

**Comment by EvanBranty** [comment]
> 我这里暂时并未成功复现该问题，也有可能是网络原因，可以再重试几次。

重启几次电脑之后直连更新成功了，感恩!

话说个人希望能在启动设置的帧数选项中加上165帧或者更高的帧数设置

**Comment by JamXi233** [comment]
暂时不会做更高帧率的选项
