### ISSUE TITLE
Tools里的画质和实际游戏画质对不上

### ISSUE THREAD

**Issue by fengziX** [JamXi233/SRTools#19]
启动游戏前检查过了画质是最低
进入游戏后发现画质是全高
是否是游戏版本更新的原因?

并且画质设置无法保存, 切换账号即失效

**Comment by JamXi233** [comment]
是游戏更新的原因，以前修改完画质并且开启120HZ会导致画质设置不显示，现在游戏内画质不会按照注册表自动同步，但画质应该是正常生效的。

**Comment by fengziX** [comment]
> 是游戏更新的原因，以前修改完画质并且开启120HZ会导致画质设置不显示，现在游戏内画质不会按照注册表自动同步，但画质应该是正常生效的。

就是说, 游戏内显示的画质设置不代表实际真实画质? 以注册表为准?

**Comment by JamXi233** [comment]
我刚才测试了一下 崩铁当前版本在使用工具箱修改画质后没有这个问题 游戏内实际画质和设置内也均改变正常[除修改特效质量为"关"的情况下游戏设置内不会改变]
