### ISSUE TITLE
下载依赖文件时显示无法建立SSL连接

### ISSUE THREAD

**Issue by iolmj** [JamXi233/SRTools#20]
![Snipaste_2024-03-27_17-06-40](https://github.com/JamXi233/SRTools/assets/127930717/5c23db39-637e-4073-a2c0-4c346c2c5803)
  如图，此前我遇上 #10 中的问题，因为觉得有些不便索性决定重装应用，问题出现在安装完成之后，遇到了与 #17 中相似的问题，但重启电脑后并未得到解决

**Comment by JamXi233** [comment]
前段时间SSL证书到期 当天已经续期 在当时问题应该已经解决了

**Comment by iolmj** [comment]
是的，当天晚上问题解决
