### ISSUE TITLE
获取首页失败，请检查网络连接

### ISSUE THREAD

**Issue by cycxiaozhi** [JamXi233/SRTools#21]
如题
![Snipaste_2024-03-29_10-42-45](https://github.com/JamXi233/SRTools/assets/165349461/ba37d68c-5465-43b6-a59a-ba493e26d294)

**Comment by JamXi233** [comment]
安装的是最新版本吗
目前最新版本是[SRTools_1.2.3.0](https://github.com/JamXi233/SRTools/releases/tag/1.2.3.0)

**Comment by cycxiaozhi** [comment]
是的



***@***.***
 
发件人： JamXi
发送时间： 2024-04-06 14:10
收件人： JamXi233/SRTools
抄送： cycxiaozhi; Author
主题： Re: [JamXi233/SRTools] 获取首页失败，请检查网络连接 (Issue #21)
安装的是最新版本吗
目前最新版本是SRTools_1.2.3.0

**Comment by JamXi233** [comment]
[SRTools_1.3.0.1](https://github.com/JamXi233/SRTools/releases/tag/1.3.0.1)已发布，可尝试使用该版本，由于我这里没有复现这个问题，故无法确定新版本是否能解决你的问题。

**Comment by cycxiaozhi** [comment]
好的，谢谢。已经安装新版本，这次好像直接没法用了，之前虽然首页报错，但还是能够正常使用其他功能的


***@***.***
 
发件人： JamXi
发送时间： 2024-04-24 13:36
收件人： JamXi233/SRTools
抄送： cycxiaozhi; Author
主题： Re: [JamXi233/SRTools] 获取首页失败，请检查网络连接 (Issue #21)
SRTools_1.3.0.1已发布，可尝试使用该版本，由于我这里没有复现这个问题，所以无法确定新版本是否能解决你的问题。

**Comment by JamXi233** [comment]
有什么错误提示吗？

**Comment by cycxiaozhi** [comment]
请问附件的图片和错误log是无法收到吗，那我去github发一下，问题提示如下：
严重错误
未指定的错误
无法在该 StorageFolder 中创建项目。如果该文件夹是在使用分组选项创建査询时获取的，则可能会出现这种情况,

已生成错误报告
如再次尝试仍会重现错误
您可以到Github提交lssue



***@***.***
 
发件人： JamXi
发送时间： 2024-04-24 17:05
收件人： JamXi233/SRTools
抄送： cycxiaozhi; Author
主题： Re: [JamXi233/SRTools] 获取首页失败，请检查网络连接 (Issue #21)
有什么错误提示吗？

**Comment by cycxiaozhi** [comment]
![Snipaste_2024-04-24_17-18-15](https://github.com/JamXi233/SRTools/assets/165349461/cfc5be3a-cb5a-482d-aaf2-888e6cba7744)
[Logs.zip](https://github.com/JamXi233/SRTools/files/15091830/Logs.zip)

**Comment by JamXi233** [comment]
请问您的[用户目录/文档/JSG-LLC]中是否有Panic目录
[用户目录/文档/JSG-LLC/SRTools]中是否有Posts目录

**Comment by cycxiaozhi** [comment]
还是就在新帖下面回复吧
