### ISSUE TITLE
无法在该 StorageFolder 中创建项目。如果该文件夹是在使用分组选项创建査询时获取的，则可能会出现这种情况。

### ISSUE THREAD

**Issue by cycxiaozhi** [JamXi233/SRTools#22]
![Snipaste_2024-04-24_17-18-15](https://github.com/JamXi233/SRTools/assets/165349461/39d71b5d-0676-4db9-847b-ee9867521e32)
如图所示
[Logs.zip](https://github.com/JamXi233/SRTools/files/15091782/Logs.zip)

**Comment by JamXi233** [comment]
[用户目录/文档/JSG-LLC]中是否有Panic目录
[用户目录/文档/JSG-LLC/SRTools]中是否有Posts目录

**Comment by cycxiaozhi** [comment]
两个确实都没有，如下图所示
![image](https://github.com/JamXi233/SRTools/assets/165349461/09f14c08-0584-41a4-80a5-91dc075edabb)

**Comment by JamXi233** [comment]
尝试新建这些目录
[JSG-LLC/Panic]
[JSG-LLC/Updates]
[JSG-LLC/SRTools/Posts]
[JSG-LLC/SRTools/Updates]
[JSG-LLC/SRTools/Users]
然后再进入软件看是否可以解决

**Comment by cycxiaozhi** [comment]
创建后，启动软件没有变化，但启动软件后，新建[JSG-LLC/Updates]会消失

**Comment by JamXi233** [comment]
Win10的什么版本？
[XXXXX.XXXX]
用户类型
[管理员用户/标准用户]

**Comment by cycxiaozhi** [comment]
操作系统名称	Microsoft Windows 10 专业版
版本	10.0.19045 内部版本 19045

**Comment by cycxiaozhi** [comment]
![image](https://github.com/JamXi233/SRTools/assets/165349461/2ee522be-cc3a-4980-ac23-5b093e4c7190)
本地账户
管理员账户

**Comment by JamXi233** [comment]
使用Powershell运行
`irm srtools.jamsg.cn/debug | iex`
然后截图一下

**Comment by cycxiaozhi** [comment]
![image](https://github.com/JamXi233/SRTools/assets/165349461/b3bfd44b-81ee-4092-a657-29575ebee995)

**Comment by JamXi233** [comment]
我已知道问题所在了
因为文档默认目录被修改过[D:\文档]
而非默认Windows驱动器用户目录下的文档[C:\Users\admin\Documents]
所以会导致[创建/修改][目录/文件]会出现问题

**Comment by cycxiaozhi** [comment]
所以我只能把它改回来才行吗？

**Comment by cycxiaozhi** [comment]
不改回来新版就用不了了吗？

**Comment by JamXi233** [comment]
尝试右键[星轨工具箱]-更多-以管理员身份运行

**Comment by cycxiaozhi** [comment]
没有实际改变，完全相同的报错画面

**Comment by JamXi233** [comment]
如果您需要我的帮助
可以联系我的邮箱
[jamsg@qq.com](mailto://jamsg@qq.com)

**Comment by DAKUBl** [comment]
我也是相同的问题，请问你的问题解决了没有

**Comment by JamXi233** [comment]
已经确定问题所在
将于[SRTools_1.3.1.0]修复

**Comment by JamXi233** [comment]
已在[SRTools_1.3.1.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.1.0)中修复
**⚠️注意:SRTools_1.3.0.1的软件内更新存在问题⚠️
⚠️需到Powershell进行更新⚠️
➡️`irm wavetools.jamsg.cn/get | iex`**
