### ISSUE TITLE
提示文件名错误

### ISSUE THREAD

**Issue by hxsdyy** [JamXi233/SRTools#23]
[SRTools_Panic_20240501_074336.zip](https://github.com/JamXi233/SRTools/files/15172269/SRTools_Panic_20240501_074336.zip)
![Snipaste_2024-05-01_07-52-55](https://github.com/JamXi233/SRTools/assets/145202516/3fe46061-8de4-4092-91e1-1710f7c9935c)
![Snipaste_2024-05-01_07-52-35](https://github.com/JamXi233/SRTools/assets/145202516/b8b11393-ed58-4135-85fe-1575bb0d7e64)

**Comment by JamXi233** [comment]
目前应已解决该问题
