### ISSUE TITLE
希望可以添加更新功能

### ISSUE THREAD

**Issue by foxlesbiao** [JamXi233/SRTools#27]
这个是我 fork 修改的更新链接 [https://github.com/foxlesbiao/StarRail_update](url)

**Comment by JamXi233** [comment]
感谢您的建议
[软件内更新游戏]将会在下版本(SRTools_1.3.1.0)加入

**Comment by foxlesbiao** [comment]
> 感谢您的建议 [软件内更新游戏] 将会在下版本 (SRTools_1.3.1.0) 加入

好的，谢谢你！

**Comment by JamXi233** [comment]
已在[SRTools_1.3.1.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.1.0)中增加[工具箱内更新/增量更新游戏]功能
**⚠️注意:SRTools_1.3.0.1的软件内更新存在问题⚠️
⚠️需到Powershell进行更新⚠️
➡️`irm wavetools.jamsg.cn/get | iex`**
