### ISSUE TITLE
可以支持一下国际服嘛

### ISSUE THREAD

**Issue by FinaFina233** [JamXi233/SRTools#28]

**Comment by JamXi233** [comment]
[添加国际服支持]将会在下版本(SRTools_1.3.1.0)加入

**Comment by FinaFina233** [comment]
> [添加国际服支持]将会在下版本(SRTools_1.3.1.0)加入

非常感谢，辛苦了

**Comment by JamXi233** [comment]
已在[SRTools_1.3.1.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.1.0)中增加国际服支持(仅限画质修改/账号切换)
**⚠️注意:SRTools_1.3.0.1的软件内更新存在问题⚠️
⚠️需到Powershell进行更新⚠️
➡️`irm wavetools.jamsg.cn/get | iex`**
