### ISSUE TITLE
一打开设置就出现这个问题，不知道是什么情况

### ISSUE THREAD

**Issue by adampan0527** [JamXi233/SRTools#29]
[SRTools_Log_20240517_185625.log](https://github.com/JamXi233/SRTools/files/15349552/SRTools_Log_20240517_185625.log)

**Comment by JamXi233** [comment]
已经确定问题所在
由于更新**JSG-API**而导致的错误，将会在稍后修复该问题。

**Comment by JamXi233** [comment]
问题已修复
