### ISSUE TITLE
可以支持一下双服切换嘛

### ISSUE THREAD

**Issue by YanWoCode** [JamXi233/SRTools#31]

**Comment by JamXi233** [comment]
B服无法使用哪些功能？

**Comment by yanwo-lab** [comment]
我是想说希望能实现双服的切换，我没有找到相关的功能
________________________________
发件人: JamXi ***@***.***>
发送时间: 2024年5月30日 13:37
收件人: JamXi233/SRTools ***@***.***>
抄送: Lzx935740 ***@***.***>; Author ***@***.***>
主题: Re: [JamXi233/SRTools] 可以支持一下B服嘛 (Issue #31)


B服无法使用哪些功能？

―

**Comment by JamXi233** [comment]
[SRTools_1.3.3.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.3.0)版本已发布
**已支持双服切换**
