### ISSUE TITLE
国际服无法修改画质，一直显示为如图，已修改过多次

### ISSUE THREAD

**Issue by FinaFina233** [JamXi233/SRTools#34]
![image](https://github.com/JamXi233/SRTools/assets/52440333/4981f4ad-05b5-48d8-b5ed-ea511b26d3b4)

**Comment by JamXi233** [comment]
[国际服无法切换画质]
会在下一版本修复

**Comment by JamXi233** [comment]
已在[SRTools_1.3.2.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.2.0)中修复
