### ISSUE TITLE
2个严重错误

### ISSUE THREAD

**Issue by aishunhao686** [JamXi233/SRTools#35]
标题：主页和抽卡记录页面在Windows 10 上不工作
内容：
我在使用Windows 10时，进入软件和进入抽卡记录页面均遇到了问题。我尝试了重新安装和查看日志，但问题依旧存在。
*操作系统：Windows 10 专业版 19045.4529
*SRTools版本：[SRTools_1.3.1.0]
曾使用过软件自带“清除所有数据”后卸载后重新安装方法尝试解决问题
附件：
*错误界面截图
![报错主页](https://github.com/JamXi233/SRTools/assets/173607733/8d2c01a4-59cd-4864-905b-11d69ae7c51c)
![报错抽卡页面](https://github.com/JamXi233/SRTools/assets/173607733/5f0f4272-eb3d-421b-9637-541a717b91c4)

*控制台错误日志截图
![主页控制台报错](https://github.com/JamXi233/SRTools/assets/173607733/251add8e-90f6-463f-8da2-f31ddde466c4)
![抽卡页面控制台报错](https://github.com/JamXi233/SRTools/assets/173607733/ca38554d-28a8-4fb3-a7ba-2ccd098c0670)

*SRToolsDebug截图
![SRToolsDebug截图](https://github.com/JamXi233/SRTools/assets/173607733/465f3566-92ca-4dec-b185-bd2721ef7a88)

**Comment by JamXi233** [comment]
是通过代理获取抽卡分析后出现这种情况吗？

**Comment by aishunhao686** [comment]
> 是通过代理获取抽卡分析后出现这种情况吗？

不是，问题1在版本更新那一天就出现了，我寻思更新了应该就能好，遂未反馈；问题2是今天更新软件版本后出现的。

**Comment by JamXi233** [comment]
系统是**官方原版**系统吗？
是否为**精简版**或**其他非官方版本**系统？

**Comment by aishunhao686** [comment]
> 系统是**官方原版**系统吗？ 是否为**精简版**或**其他非官方版本**系统？

这系统装2年多了，应该是在某网站上找的纯净版、后续自行注册的系统

**Comment by aishunhao686** [comment]
> 系统是**官方原版**系统吗？ 是否为**精简版**或**其他非官方版本**系统？

今天更新版本重装了一下，所有功能都能正常使用了；但是不能导入以前的备份数据，一旦导入就和以前一样报错。

**Comment by JamXi233** [comment]
因为之前的数据本身是错误的，所以无法导入。
