### ISSUE TITLE
代理获取抽卡记录失败

### ISSUE THREAD

**Issue by cenbide** [JamXi233/SRTools#37]
开启代理后获取了抽卡记录，查看本地文件发现是已经生成了三个带有不同池子抽卡记录的json文件，但是工具箱未能成功读取本地文件无法展示然后报错 无法找到与此错误代码关联的文本。

找不到具有指定名称(JSG-LLC\SRTools\GachaRecords\100661533)的
项目。点击不同池子也会触发相同错误，删除抽卡记录json重新生成后也会报相同错误
![image](https://github.com/JamXi233/SRTools/assets/49063453/cc07dc8b-9e8c-4357-a738-ee006fd7708a)
![image](https://github.com/JamXi233/SRTools/assets/49063453/e0535e8b-d42e-436a-997e-fdbbb2832f14)
![image](https://github.com/JamXi233/SRTools/assets/49063453/833ee7c9-3c35-4373-8517-48193e5eea7f)

**Comment by FluereL** [comment]
存在类似的情况，无法显示抽卡记录并弹出错误提示，但提示文本不同。GachaRecords 文件夹有三个记录抽卡记录的 ini 文件。
操作系统：Windows 10 19045.0
SRTools版本：SRTools_1.3.2.0
![Snipaste_2024-07-03_22-55-06](https://github.com/JamXi233/SRTools/assets/33753435/5a61278c-8622-4b7f-b6c9-e081e7fdfc01)
![Snipaste_2024-07-03_22-54-43](https://github.com/JamXi233/SRTools/assets/33753435/3549285d-c02a-4e44-b899-1a5861ffb348)
![Snipaste_2024-07-03_22-50-35](https://github.com/JamXi233/SRTools/assets/33753435/61108c3a-00f0-45dd-a5da-2585abb7827d)

**Comment by JamXi233** [comment]
@FluereL 
您的问题是由于**抽卡记录获取不完整**导致的
有可能是SRTools正在获取抽卡记录的时候您同时在游戏中**点击了抽卡记录的上一页或下一页**
可以尝试清空记录后重新开启代理再次获取，在获取过程中**不要操作游戏中的抽卡记录**。

**Comment by FluereL** [comment]
了解了，感谢

**Comment by JamXi233** [comment]
@cenbide 
[SRTools_1.3.3.0](https://github.com/JamXi233/SRTools/releases/tag/1.3.3.0)版本已发布，可尝试之前有问题的操作观察是否会再次复现问题

**Comment by JamXi233** [comment]
已经超过两周没有收到回复，将关闭该issue。
