### ISSUE TITLE
无法完成1.1.0.0的依赖更新

### ISSUE THREAD

**Issue by BUAA-David** [JamXi233/SRTools#41]
![image](https://github.com/user-attachments/assets/b8a0b5e2-f95a-411a-9e83-e6900a1c8fb5)
两种更新渠道均已尝试过，都会出现图中错误。
![image](https://github.com/user-attachments/assets/92aed999-15f1-45ff-92dd-ccf629371e67)
进而导致上图问题。

**Comment by jiamin-2026** [comment]
操作系统：Windows 11 22631.4037

SRTools_1.3.9.0

**Comment by jiamin-2026** [comment]
![image](https://github.com/user-attachments/assets/9451e9ec-a5c3-41e1-92f1-5a0fcbbf40d8)
这个是开启控制台后的详细信息。

**Comment by jiamin-2026** [comment]
在磁盘上检索所有带有"SRTools"字符串的文件并删除，最后再重新安装就没问题了。（）
![image](https://github.com/user-attachments/assets/1b1e1752-b586-4cd2-8569-d2ebc849d806)
![image](https://github.com/user-attachments/assets/d3586b98-15f9-4c35-a396-42599d9f43ab)
