### ISSUE TITLE
老版本跃迁记录升级失败

### ISSUE THREAD

**Issue by Oops418** [JamXi233/SRTools#42]
报错界面：
![image](https://github.com/user-attachments/assets/78c48b9b-c3a2-41a8-9468-994e220a8ba8)

![image](https://github.com/user-attachments/assets/d56494c8-89ab-4b48-82e7-39d3c0b35f37)

错误日志：
![image](https://github.com/user-attachments/assets/fe69b528-c8e4-451a-8ca8-c78b35891a2b)

SRToolsDebug截图：
![image](https://github.com/user-attachments/assets/17b59519-da51-4fcb-83bf-cb0f0b793723)

日志文件：
[SRTools_Log_20240825_220400.log](https://github.com/user-attachments/files/16740600/SRTools_Log_20240825_220400.log)
[SRTools_Panic_20240825_221213.SRToolsPanic.txt](https://github.com/user-attachments/files/16740595/SRTools_Panic_20240825_221213.SRToolsPanic.txt)

**Comment by JamXi233** [comment]
可能是升级版本跨度过大导致的
可以将您目前的抽卡记录发送到我的邮箱
jamsg@qq.com
抽卡记录位于[文档\JSG-LLC\SRTools\GachaRecords]

**Comment by JamXi233** [comment]
好的，我已经收到了您的抽卡记录。
看起来您应该是从1.2版本升级到了最新版本。
1.2版本时期还没有多用户抽卡分析，在1.3.4.0中已经丢弃了单用户转多用户的转换方法。
### 您可以尝试的步骤：
- 安装[1.3.0.1](https://github.com/JamXi233/SRTools/releases/tag/1.3.0.1)版本(1.3.0.0的修复版本) **```可以直接下载msix进行覆盖安装，如果覆盖安装失败就需要先卸载然后再安装```**
- 查看抽卡分析是否正常 ```可选：您可以导出一份记录(SRGF格式)，防止丢失。```
- 查看[文档\JSG-LLC\SRTools\GachaRecords]中是否出现了您的UID文件夹。
- 正常升级到最新版本后再次进行抽卡记录更新。

**Comment by Oops418** [comment]
您好，进行覆盖安装/先卸载后安装后出现了新的问题，并且一打开就会报错
这是报错界面：
![image](https://github.com/user-attachments/assets/cecba83d-4f91-4a94-83d8-2ff52bb2c5f8)
这是报错信息和日志：
[SRTools_Panic_20240831_132721.SRToolsPanic.txt](https://github.com/user-attachments/files/16823555/SRTools_Panic_20240831_132721.SRToolsPanic.txt)
[SRTools_Log_20240831_133115.log](https://github.com/user-attachments/files/16823556/SRTools_Log_20240831_133115.log)

**Comment by Oops418** [comment]
您好，我已经解决了我的问题。

1.3.0.1版本出错是因为接口 https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/content?filter_adv=false&key=6KcVuOkbcqjJomjZ&language=zh-cn&launcher_id=33 中数据结构发生改变，adv的取值为null所以报错。

后续我从1.3.1.0源码编译进入后，无法显示角色抽卡记录，发现不知道什么时候我的抽卡记录的文件中写入了一条空记录，因此无法显示角色抽卡记录
<img width="1082" alt="Snipaste_2024-09-09_23-31-29" src="https://github.com/user-attachments/assets/baf904a3-e2e9-4727-9cf7-d29de2e63282">
我手动删除这条空记录后即可正常显示角色池的抽卡记录
后续升级到最新版本并升级抽卡记录版本一切正常
ps：如果有人出现了和我同样的报错，可以先检查老版本抽卡记录文件中，是否出现了null的情况，手动删除后再次尝试升级
