### ISSUE TITLE
符号出错，问问是哪款字体

### ISSUE THREAD

**Issue by juruo123** [JamXi233/SRTools#5]
![image](https://github.com/JamXi233/SRTools/assets/46376417/beda2867-0723-4e0d-a320-84492f218535)
好像没看到调节字体的选项，不知道缺了哪个字体

**Comment by JamXi233** [comment]
发一下系统版本

**Comment by juruo123** [comment]
> 发一下系统版本

windows10 专业版22H2 19045.3208

**Comment by JamXi233** [comment]
尝试安装Segoe MDL2字体
[https://aka.ms/SegoeFonts](https://aka.ms/SegoeFonts)

**Comment by juruo123** [comment]
好了，但是似乎没有什么变化

**Comment by JamXi233** [comment]
将会在下一版本均改为SegoeFluentIcons图标，并在设置中添加自动安装缺失字体的选项
