### ISSUE TITLE
另一个程序正在使用此文件，无法访问

### ISSUE THREAD

**Issue by yiqiqiaoqiaode** [JamXi233/SRTools#6]

**Comment by yiqiqiaoqiaode** [comment]
2023/8/6 13:04:22 [1] 
 应用程序：System.Net.Http
 错误标题:无法建立 SSL 连接，请参阅内部异常。
 堆栈跟踪：
    在 System.Net.Http.ConnectHelper.EstablishSslConnectionAsync（SslClientAuthenticationOptions sslOptions、HttpRequestMessage 请求、布尔异步、流流、CancellationToken CancellationToken）
    在System.Net.Http.HttpConnectionPool.ConnectAsync（HttpRequestMessage请求，布尔异步，CancellationToken取消令牌）
    在System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync（HttpRequestMessage请求，布尔异步，CancellationToken取消令牌）
    在 System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem 队列项)
    在 System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken CancellationToken)
    在 System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync（布尔异步，CancellationToken requestCancellationToken）
    在 System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync（HttpRequestMessage 请求，布尔异步，布尔 doRequestAuth，CancellationToken CancellationToken）
    在System.Net.Http.RedirectHandler.SendAsync（HttpRequestMessage请求，布尔异步，CancellationToken取消令牌）
    在System.Net.Http.HttpClient.<SendAsync>g__Core | 83_0（HttpRequestMessage请求，HttpCompletionOption完成选项，CancellationTokenSource cts，布尔disposeCts，CancellationTokenSource挂起RequestsCts，CancellationToken原始CancellationToken）
    在 SRTools.Views.AboutView.GetVersionButton_Click（对象发送者，RotedEventArgs e）
    在 System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0（对象状态）
    在 Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
 --- 先前位置的堆栈跟踪结束 ---
    在 WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0（Int32 小时）
    在 ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
    在 Windows.ApplicationModel.Core.UnhandledError.Propagate()
    在 SRTools.MainWindow.OnUnhandledErrorDetected（对象发送者，UnhandledErrorDetectedEventArgs e）
 结束代码:-2146233087

**Comment by JamXi233** [comment]
SSL证书到期，预计在一段时间内修复完成

**Comment by JamXi233** [comment]
已修复
