### ISSUE TITLE
严重错误

### ISSUE THREAD

**Issue by NOWorEVER** [JamXi233/SRTools#9]
首页提示严重错误
![image](https://github.com/JamXi233/SRTools/assets/57054154/5288b7be-08cd-4311-b5e5-512fa420e4f4)
无法打开文件夹，点击后会直接卡死
![image](https://github.com/JamXi233/SRTools/assets/57054154/e37cacd5-8e1d-4c67-85b2-8d437e59eb4c)
包括点击选择游戏本体

**Comment by JamXi233** [comment]
将错误报告上传一下

**Comment by NOWorEVER** [comment]
这个是在控制器里面复制的，我在根目录没找到错误日志

  at async void OnUnhandledErrorDetected(object sender,
     UnhandledErrorDetectedEventArgs e)
COMException: 未指定的错误

  at async Task Write(string message, int severity, string
     fileName)
  at async void OnUnhandledErrorDetected(object sender,
     UnhandledErrorDetectedEventArgs e)
  at void <ThrowAsync>b__128_0(object state)
  at void <Post>b__0()
  at void <ThrowExceptionForHR>g__Throw|20_0(int hr)
  at async void OnUnhandledErrorDetected(object sender,
     UnhandledErrorDetectedEventArgs e)
COMException: 未指定的错误

  at async Task Write(string message, int severity, string
     fileName)
  at async void OnUnhandledErrorDetected(object sender,
     UnhandledErrorDetectedEventArgs e)
  at void <ThrowAsync>b__128_0(object state)
  at void <Post>b__0()
  at void <ThrowExceptionForHR>g__Throw|20_0(int hr)
  at async void OnUnhandledErrorDetected(object sender,
     UnhandledErrorDetectedEventArgs e)

**Comment by JamXi233** [comment]
系统的版本:Windows [XX] XXXXX.XXXX
用户类型:
软件安装方式:

**Comment by NOWorEVER** [comment]
系统的版本: Windows 10 专业版 22H2
用户类型:默认用户
软件安装方式:右键Install.ps1使用powershell安装

**Comment by JamXi233** [comment]
请提供Windows的内部版本号
以及用户类型[Microsoft用户、本地用户]，[标准用户、管理员用户]

**Comment by NOWorEVER** [comment]
内部版本号：19045.3693
用户类型：本地用户  管理员用户

**Comment by JamXi233** [comment]
在首次设置时候 下载依赖文件没有任何问题吗

**Comment by NOWorEVER** [comment]
没有，都是正常下载的，刚刚使用控制模式成功添加游戏路径了，现在这个界面点两下就开始报错，之前的版本只有获取主页失败，其他功能正常
![image](https://github.com/JamXi233/SRTools/assets/57054154/e4e99395-5256-43f8-928a-49afe69e6ed7)
现在点两下就开始报错
![image](https://github.com/JamXi233/SRTools/assets/57054154/c2865a11-0335-4944-a1f0-f2bd2eb1e782)

**Comment by JamXi233** [comment]
有可能是系统的COM加载项问题，可以尝试重装官方系统解决问题

**Comment by NOWorEVER** [comment]
新版本后解决奔溃问题了，但是主页还是有【获取首页失败，请检查网络连接】
![Uploading image.png…]()

**Comment by JamXi233** [comment]
使用Powershell运行
irm srtools.jamsg.cn/debug | iex
然后截图一下

**Comment by xiaofeicoding** [comment]
@JamXi233   和我这个情况是一样的  
![2798703b6dbaa7bb355c6455e2e5baf](https://github.com/JamXi233/SRTools/assets/120693871/6d93eedc-c159-43c7-8c20-0d38314911d9)

**Comment by JamXi233** [comment]
> @JamXi233 和我这个情况是一样的 ![2798703b6dbaa7bb355c6455e2e5baf](https://private-user-images.githubusercontent.com/120693871/330654669-6d93eedc-c159-43c7-8c20-0d38314911d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTkyMjgsIm5iZiI6MTcxNTk5ODkyOCwicGF0aCI6Ii8xMjA2OTM4NzEvMzMwNjU0NjY5LTZkOTNlZWRjLWMxNTktNDNjNy04YzIwLTBkMzgzMTQ5MTFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwMjIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTY3OGEwYjYwNjMzMDVjYTRiMGJmMTJjNWNjYmQ1MjVkMzM5MThlNjc2YWFkOTU4YTBiZDU5ZDkwNzk5MjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yN9ilXggO_T4qnzFD6rmvTVjY5P24X8xQ0h0iH9TVAg)

能否附上日志文件/错误日志文件呢 位置详见 #25

**Comment by zganbaisan** [comment]
![676}Z5}YK@}T%PPEGU14ETS](https://github.com/JamXi233/SRTools/assets/170539688/3ec77728-2342-453f-9e7f-f3eff934b6e0)
![image](https://github.com/JamXi233/SRTools/assets/170539688/51f926d4-d36a-44ee-b49c-877df1a39475)
抽卡记录开启代理之后出来错误

**Comment by JamXi233** [comment]
@zganbaisan 请新开issue 按照 #25 的提问示例

**Comment by JamXi233** [comment]
@NOWorEVER 目前最新版本还有问题吗？

**Comment by NOWorEVER** [comment]
> @NOWorEVER 目前最新版本还有问题吗？

没有了，也可能是因为后续重装了系统，先关闭吧，感谢大佬

**Comment by JamXi233** [comment]
好的，将关闭该issue。
